### ISSUE TITLE
how to solve this problem

### ISSUE THREAD

**Issue by Raindreem** [ZekerZhayard/CompatibilityLayerForCustomSkinLoader#1]
[minecraft-exported-crash-info-2022-03-21T12-03-40.zip](https://github.com/ZekerZhayard/CompatibilityLayerForCustomSkinLoader/files/8313004/minecraft-exported-crash-info-2022-03-21T12-03-40.zip)

**Comment by ZekerZhayard** [comment]
是 littleMaidMobX 的写法过于高血压了

**Comment by ZekerZhayard** [comment]
已经在 ALPHA-8 版本修复
